kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: llm-d-scale-epp
rules:
- apiGroups: ["inference.networking.k8s.io"]
  resources: ["inferencepools", "inferenceobjectives"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferenceobjectives", "inferencemodels", "inferencepools"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create