apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-d-scale-epp
data:
  load-aware.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: max-score-picker
    - type: load-aware-scorer
    - type: single-profile-handler
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: load-aware-scorer
        weight: 1
      - pluginRef: max-score-picker
  default.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: max-score-picker
    - type: single-profile-handler
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: max-score-picker
  epp-estimate-prefix-cache-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: single-profile-handler
    - type: decode-filter
    - type: prefix-cache-scorer
    - type: load-aware-scorer
    - type: max-score-picker
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: decode-filter
      - pluginRef: prefix-cache-scorer
        weight: 1.0
      - pluginRef: load-aware-scorer
        weight: 1.0
      - pluginRef: max-score-picker
  epp-precise-prefix-cache-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
      - type: single-profile-handler
      - type: decode-filter
      - type: precise-prefix-cache-scorer
        parameters:
          indexerConfig:
            tokenProcessorConfig:
              blockSize: 64                 # must match vLLM block size
              hashSeed: "42"                # must match vLLM PYTHONHASHSEED env var
            kvBlockIndexConfig:
              enableMetrics: true           # enable kv-block index metrics (prometheus)
      - type: kv-cache-utilization-scorer
      - type: queue-scorer
      - type: max-score-picker
    schedulingProfiles:
      - name: default
        plugins:
          - pluginRef: decode-filter
          - pluginRef: precise-prefix-cache-scorer
            weight: 2.0
          - pluginRef: kv-cache-utilization-scorer
            weight: 1.0
          - pluginRef: queue-scorer
            weight: 1.0
          - pluginRef: max-score-picker