apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-d-scale-model-server
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: llm-d-scale
  template:
    metadata:
      labels:
        app: llm-d-scale
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
        - name: vllm
          image: ghcr.io/llm-d/llm-d-inference-sim:v0.5.1
          args:
            - --config
            - config/config.yml
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PYTHONHASHSEED
            value: "42"
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: llm-d-hf-token
                key: HF_TOKEN
          ports:
          - containerPort: 8000
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: sim-config
    
