apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-d-scale-model-server
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: llm-d-scale
  template:
    metadata:
      labels:
        app: llm-d-scale
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/gpu
                operator: Exists
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
        - name: vllm
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          image: {{ .image }}
          command: ["/bin/sh", "-c"]
          args: [
          "vllm {{ .flags }}"
          ]
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonRoot: false
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: llm-d-hf-token
                key: HF_TOKEN
          ports:
          - containerPort: 8000
            protocol: TCP
    
